name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Super-Linter
        uses: github/super-linter@v4.9.5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
